load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "filters",
    srcs = ["hole_marker_id.go"],
    importpath = "github.com/jacobbrewer1/golf-data/pkg/repositories/processor/filters",
    visibility = ["//visibility:public"],
    deps = ["@com_github_jacobbrewer1_patcher//:patcher"],
)
