// Package dataapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dataapi

import (
	externalRef0 "github.com/jacobbrewer1/pagefilter/common"
)

// Club defines the model for club.
type Club struct {
	Address1 *string `json:"address1,omitempty"`
	Address2 *string `json:"address2,omitempty"`
	Address3 *string `json:"address3,omitempty"`
	City     *string `json:"city,omitempty"`
	Id       *int64  `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Postcode *string `json:"postcode,omitempty"`
}

// QueryNameParam defines the model for query_name_param.
type QueryNameParam = string

// GetClubsResponse defines the model for get_clubs_response.
type GetClubsResponse struct {
	Items *[]Club `json:"items,omitempty"`
	Total *int64  `json:"total,omitempty"`
}

// GetClubsParams defines parameters for GetClubs.
type GetClubsParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// Offset Pagination details, offset value.
	Offset *externalRef0.Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetClubsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// Name The name of the club
	Name *QueryNameParam `form:"name,omitempty" json:"name,omitempty"`
}

// GetClubsParamsSortDir defines parameters for GetClubs.
type GetClubsParamsSortDir string
