// Code generated by mockery. DO NOT EDIT.

package domain

import (
	models "github.com/jacobbrewer1/golf-data/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockDomain is an autogenerated mock type for the Domain type
type MockDomain struct {
	mock.Mock
}

// SaveClub provides a mock function with given fields: club
func (_m *MockDomain) SaveClub(club *models.Club) error {
	ret := _m.Called(club)

	if len(ret) == 0 {
		panic("no return value specified for SaveClub")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Club) error); ok {
		r0 = rf(club)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveCourse provides a mock function with given fields: course
func (_m *MockDomain) SaveCourse(course *models.Course) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for SaveCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Course) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveDetails provides a mock function with given fields: details
func (_m *MockDomain) SaveDetails(details *models.CourseDetails) error {
	ret := _m.Called(details)

	if len(ret) == 0 {
		panic("no return value specified for SaveDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.CourseDetails) error); ok {
		r0 = rf(details)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveHole provides a mock function with given fields: holes
func (_m *MockDomain) SaveHole(holes *models.Hole) error {
	ret := _m.Called(holes)

	if len(ret) == 0 {
		panic("no return value specified for SaveHole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Hole) error); ok {
		r0 = rf(holes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDomain creates a new instance of MockDomain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomain(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomain {
	mock := &MockDomain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
