// Code generated by mockery. DO NOT EDIT.

package domain

import (
	api "github.com/jacobbrewer1/golf-data/pkg/apis/specs/api"
	mock "github.com/stretchr/testify/mock"

	pagefilter "github.com/jacobbrewer1/pagefilter"
)

// MockDomain is an autogenerated mock type for the Domain type
type MockDomain struct {
	mock.Mock
}

// GetClubs provides a mock function with given fields: paginatorDetails, params
func (_m *MockDomain) GetClubs(paginatorDetails *pagefilter.PaginatorDetails, params *api.GetClubsParams) (*api.GetClubsResponse, error) {
	ret := _m.Called(paginatorDetails, params)

	if len(ret) == 0 {
		panic("no return value specified for GetClubs")
	}

	var r0 *api.GetClubsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *api.GetClubsParams) (*api.GetClubsResponse, error)); ok {
		return rf(paginatorDetails, params)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *api.GetClubsParams) *api.GetClubsResponse); ok {
		r0 = rf(paginatorDetails, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetClubsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, *api.GetClubsParams) error); ok {
		r1 = rf(paginatorDetails, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourses provides a mock function with given fields: paginatorDetails, clubID, params
func (_m *MockDomain) GetCourses(paginatorDetails *pagefilter.PaginatorDetails, clubID int64, params *api.GetCoursesParams) (*api.GetCoursesResponse, error) {
	ret := _m.Called(paginatorDetails, clubID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetCourses")
	}

	var r0 *api.GetCoursesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, int64, *api.GetCoursesParams) (*api.GetCoursesResponse, error)); ok {
		return rf(paginatorDetails, clubID, params)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, int64, *api.GetCoursesParams) *api.GetCoursesResponse); ok {
		r0 = rf(paginatorDetails, clubID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetCoursesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, int64, *api.GetCoursesParams) error); ok {
		r1 = rf(paginatorDetails, clubID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHoles provides a mock function with given fields: paginatorDetails, markerId, params
func (_m *MockDomain) GetHoles(paginatorDetails *pagefilter.PaginatorDetails, markerId int64, params *api.GetHolesParams) (*api.GetHolesResponse, error) {
	ret := _m.Called(paginatorDetails, markerId, params)

	if len(ret) == 0 {
		panic("no return value specified for GetHoles")
	}

	var r0 *api.GetHolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, int64, *api.GetHolesParams) (*api.GetHolesResponse, error)); ok {
		return rf(paginatorDetails, markerId, params)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, int64, *api.GetHolesParams) *api.GetHolesResponse); ok {
		r0 = rf(paginatorDetails, markerId, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetHolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, int64, *api.GetHolesParams) error); ok {
		r1 = rf(paginatorDetails, markerId, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMarkers provides a mock function with given fields: paginatorDetails, courseID, params
func (_m *MockDomain) GetMarkers(paginatorDetails *pagefilter.PaginatorDetails, courseID int64, params *api.GetMarkersParams) (*api.GetMarkersResponse, error) {
	ret := _m.Called(paginatorDetails, courseID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkers")
	}

	var r0 *api.GetMarkersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, int64, *api.GetMarkersParams) (*api.GetMarkersResponse, error)); ok {
		return rf(paginatorDetails, courseID, params)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, int64, *api.GetMarkersParams) *api.GetMarkersResponse); ok {
		r0 = rf(paginatorDetails, courseID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetMarkersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, int64, *api.GetMarkersParams) error); ok {
		r1 = rf(paginatorDetails, courseID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDomain creates a new instance of MockDomain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomain(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomain {
	mock := &MockDomain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
