// Code generated by mockery. DO NOT EDIT.

package api

import (
	models "github.com/jacobbrewer1/golf-data/pkg/models"
	mock "github.com/stretchr/testify/mock"

	pagefilter "github.com/jacobbrewer1/pagefilter"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// GetClubs provides a mock function with given fields: details, filter
func (_m *MockRepository) GetClubs(details *pagefilter.PaginatorDetails, filter *GetClubsFilters) (*pagefilter.PaginatedResponse[models.Club], error) {
	ret := _m.Called(details, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetClubs")
	}

	var r0 *pagefilter.PaginatedResponse[models.Club]
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetClubsFilters) (*pagefilter.PaginatedResponse[models.Club], error)); ok {
		return rf(details, filter)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetClubsFilters) *pagefilter.PaginatedResponse[models.Club]); ok {
		r0 = rf(details, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagefilter.PaginatedResponse[models.Club])
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, *GetClubsFilters) error); ok {
		r1 = rf(details, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourses provides a mock function with given fields: details, filter
func (_m *MockRepository) GetCourses(details *pagefilter.PaginatorDetails, filter *GetCoursesFilters) (*pagefilter.PaginatedResponse[models.Course], error) {
	ret := _m.Called(details, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCourses")
	}

	var r0 *pagefilter.PaginatedResponse[models.Course]
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetCoursesFilters) (*pagefilter.PaginatedResponse[models.Course], error)); ok {
		return rf(details, filter)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetCoursesFilters) *pagefilter.PaginatedResponse[models.Course]); ok {
		r0 = rf(details, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagefilter.PaginatedResponse[models.Course])
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, *GetCoursesFilters) error); ok {
		r1 = rf(details, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHoles provides a mock function with given fields: details, filter
func (_m *MockRepository) GetHoles(details *pagefilter.PaginatorDetails, filter *GetHolesFilters) (*pagefilter.PaginatedResponse[models.Hole], error) {
	ret := _m.Called(details, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetHoles")
	}

	var r0 *pagefilter.PaginatedResponse[models.Hole]
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetHolesFilters) (*pagefilter.PaginatedResponse[models.Hole], error)); ok {
		return rf(details, filter)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetHolesFilters) *pagefilter.PaginatedResponse[models.Hole]); ok {
		r0 = rf(details, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagefilter.PaginatedResponse[models.Hole])
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, *GetHolesFilters) error); ok {
		r1 = rf(details, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMarkers provides a mock function with given fields: details, filter
func (_m *MockRepository) GetMarkers(details *pagefilter.PaginatorDetails, filter *GetMarkersFilters) (*pagefilter.PaginatedResponse[models.CourseDetails], error) {
	ret := _m.Called(details, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkers")
	}

	var r0 *pagefilter.PaginatedResponse[models.CourseDetails]
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetMarkersFilters) (*pagefilter.PaginatedResponse[models.CourseDetails], error)); ok {
		return rf(details, filter)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *GetMarkersFilters) *pagefilter.PaginatedResponse[models.CourseDetails]); ok {
		r0 = rf(details, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagefilter.PaginatedResponse[models.CourseDetails])
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, *GetMarkersFilters) error); ok {
		r1 = rf(details, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
