// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"strings"

	"github.com/jacobbrewer1/patcher"
	"github.com/jacobbrewer1/patcher/inserter"
	"github.com/prometheus/client_golang/prometheus"
)

const (
	// ClubTableName is the name of the table for the Club model.
	ClubTableName = "club"
)

// Club represents a row from 'club'.
type Club struct {
	Id         int    `db:"id,pk,autoinc"`
	Name       string `db:"name"`
	Address1   string `db:"address1"`
	Address2   string `db:"address2"`
	Address3   string `db:"address3"`
	Address4   string `db:"address4"`
	PostalCode string `db:"postal_code"`
}

// Insert inserts the Club to the database.
func (m *Club) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_" + ClubTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO club (" +
		"`name`, `address1`, `address2`, `address3`, `address4`, `postal_code`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode)
	res, err := db.Exec(sqlstr, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func (m *Club) InsertClubWithPK(db DB) error {
	if !m.IsPrimaryKeySet() {
		return ErrNoPK
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_with_ids_" + ClubTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO club (" +
		"`id`, `name`, `address1`, `address2`, `address3`, `address4`, `postal_code`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.Id, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode)
	_, err := db.Exec(sqlstr, m.Id, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode)
	return err
}

func InsertManyClubs(db DB, ms ...*Club) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_" + ClubTableName))
	defer t.ObserveDuration()

	vals := make([]any, 0, len(ms))
	for _, m := range ms {
		// Dereference the pointer to get the struct value.
		vals = append(vals, any(*m))
	}

	sqlstr, args, err := inserter.NewBatch(vals, inserter.WithTable(ClubTableName)).GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to create batch insert: %w", err)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *Club) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the Club in the database.
func (m *Club) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_" + ClubTableName))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE club " +
		"SET `name` = ?, `address1` = ?, `address2` = ?, `address3` = ?, `address4` = ?, `postal_code` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode, m.Id)
	res, err := db.Exec(sqlstr, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the Club to the database, and tries to update
// on unique constraint violations.
func (m *Club) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_" + ClubTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO club (" +
		"`name`, `address1`, `address2`, `address3`, `address4`, `postal_code`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`name` = VALUES(`name`), `address1` = VALUES(`address1`), `address2` = VALUES(`address2`), `address3` = VALUES(`address3`), `address4` = VALUES(`address4`), `postal_code` = VALUES(`postal_code`)"

	DBLog(sqlstr, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode)
	res, err := db.Exec(sqlstr, m.Name, m.Address1, m.Address2, m.Address3, m.Address4, m.PostalCode)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the Club to the database.
func (m *Club) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the Club to the database, but tries to update
// on unique constraint violations.
func (m *Club) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the Club from the database.
func (m *Club) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_" + ClubTableName))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM club WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// ClubById retrieves a row from 'club' as a Club.
//
// Generated from primary key.
func ClubById(db DB, id int) (*Club, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_" + ClubTableName + "_by_id"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `name`, `address1`, `address2`, `address3`, `address4`, `postal_code` " +
		"FROM club " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m Club
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

type clubPKWherer struct {
	ids []any
}

func (m clubPKWherer) Where() (string, []any) {
	return "`id` = ?", m.ids
}

// Patch updates the Club in the database.
//
// Generated from primary key.
func (m *Club) Patch(db DB, newT *Club) error {
	if newT == nil {
		return errors.New("new primary is nil")
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("patch_" + ClubTableName))
	defer t.ObserveDuration()

	res, err := patcher.NewDiffSQLPatch(
		m,
		newT,
		patcher.WithTable(ClubTableName),
		patcher.WithWhere(&clubPKWherer{
			ids: []any{m.Id},
		}),
		patcher.WithIgnoredFields(
			"Id",
		),
	)
	if err != nil {
		switch {
		case errors.Is(err, patcher.ErrNoChanges):
			return nil
		default:
			return fmt.Errorf("new diff sql patch: %w", err)
		}
	}

	sqlstr, args, err := res.GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to generate patch: %w", err)
	}

	DBLog(sqlstr, args...)
	_, err = db.Exec(sqlstr, args...)
	if err != nil {
		return fmt.Errorf("failed to execute patch: %w", err)
	}

	return nil
}

// ClubByName retrieves a row from 'club' as a *Club.
//
// Generated from index ” of type 'unique'.
func ClubByName(db DB, name string) (*Club, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_" + ClubTableName + "_by_name"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `name`, `address1`, `address2`, `address3`, `address4`, `postal_code` " +
		"FROM club " +
		"WHERE `name` = ?"

	DBLog(sqlstr, name)
	var m Club
	if err := db.Get(&m, sqlstr, name); err != nil {
		return nil, err
	}

	return &m, nil
}

// GetAllClubs retrieves all rows from 'club' as a slice of Club.
//
// Generated from table 'club'.
func GetAllClubs(db DB, filters ...any) ([]*Club, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_all_" + ClubTableName))
	defer t.ObserveDuration()

	args := make([]any, 0)
	builder := new(strings.Builder)
	builder.WriteString("SELECT t.id, t.name, t.address1, t.address2, t.address3, t.address4, t.postal_code")

	if len(filters) > 0 {
		for _, filter := range filters {
			joiner, ok := filter.(patcher.Joiner)
			if ok {
				joinSql, joinArgs := joiner.Join()
				builder.WriteString(joinSql)
				args = append(args, joinArgs...)
			}
		}
	}

	builder.WriteString("\nFROM club t")

	if len(filters) > 0 {
		builder.WriteString("\nWHERE\n")
		for i, filter := range filters {
			where, ok := filter.(patcher.Wherer)
			if ok {
				if i > 0 {
					wtStr := patcher.WhereTypeAnd
					if wt, ok := filter.(patcher.WhereTyper); ok {
						wtStr = wt.WhereType()
					}
					builder.WriteString(string(" " + wtStr + " "))
				}
				whereSql, whereArgs := where.Where()
				builder.WriteString(whereSql)
				builder.WriteString("\n")
				args = append(args, whereArgs...)
			}
		}
	}

	sqlstr := builder.String()
	DBLog(sqlstr, args...)

	m := make([]*Club, 0)
	if err := db.Select(&m, sqlstr, args...); err != nil {
		return nil, fmt.Errorf("failed to get all Club: %w", err)
	}

	return m, nil
}
