// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"strings"

	"github.com/jacobbrewer1/goschema/usql"
	"github.com/jacobbrewer1/patcher"
	"github.com/jacobbrewer1/patcher/inserter"
	"github.com/prometheus/client_golang/prometheus"
)

const (
	// CourseDetailsTableName is the name of the table for the CourseDetails model.
	CourseDetailsTableName = "course_details"
)

// CourseDetails represents a row from 'course_details'.
type CourseDetails struct {
	Id              int             `db:"id,pk,autoinc"`
	CourseId        int             `db:"course_id"`
	Marker          usql.NullString `db:"marker"`
	Slope           int             `db:"slope"`
	CourseRating    float64         `db:"course_rating"`
	FrontNinePar    int             `db:"front_nine_par"`
	BackNinePar     int             `db:"back_nine_par"`
	TotalPar        int             `db:"total_par"`
	FrontNineYards  int             `db:"front_nine_yards"`
	BackNineYards   int             `db:"back_nine_yards"`
	TotalYards      int             `db:"total_yards"`
	FrontNineMeters int             `db:"front_nine_meters"`
	BackNineMeters  int             `db:"back_nine_meters"`
	TotalMeters     int             `db:"total_meters"`
}

// Insert inserts the CourseDetails to the database.
func (m *CourseDetails) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO course_details (" +
		"`course_id`, `marker`, `slope`, `course_rating`, `front_nine_par`, `back_nine_par`, `total_par`, `front_nine_yards`, `back_nine_yards`, `total_yards`, `front_nine_meters`, `back_nine_meters`, `total_meters`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters)
	res, err := db.Exec(sqlstr, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func (m *CourseDetails) InsertCourseDetailsWithPK(db DB) error {
	if !m.IsPrimaryKeySet() {
		return ErrNoPK
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_with_ids_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO course_details (" +
		"`id`, `course_id`, `marker`, `slope`, `course_rating`, `front_nine_par`, `back_nine_par`, `total_par`, `front_nine_yards`, `back_nine_yards`, `total_yards`, `front_nine_meters`, `back_nine_meters`, `total_meters`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.Id, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters)
	_, err := db.Exec(sqlstr, m.Id, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters)
	return err
}

func InsertManyCourseDetailss(db DB, ms ...*CourseDetails) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	vals := make([]any, 0, len(ms))
	for _, m := range ms {
		// Dereference the pointer to get the struct value.
		vals = append(vals, any(*m))
	}

	sqlstr, args, err := inserter.NewBatch(vals, inserter.WithTable(CourseDetailsTableName)).GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to create batch insert: %w", err)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *CourseDetails) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the CourseDetails in the database.
func (m *CourseDetails) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE course_details " +
		"SET `course_id` = ?, `marker` = ?, `slope` = ?, `course_rating` = ?, `front_nine_par` = ?, `back_nine_par` = ?, `total_par` = ?, `front_nine_yards` = ?, `back_nine_yards` = ?, `total_yards` = ?, `front_nine_meters` = ?, `back_nine_meters` = ?, `total_meters` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters, m.Id)
	res, err := db.Exec(sqlstr, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the CourseDetails to the database, and tries to update
// on unique constraint violations.
func (m *CourseDetails) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO course_details (" +
		"`course_id`, `marker`, `slope`, `course_rating`, `front_nine_par`, `back_nine_par`, `total_par`, `front_nine_yards`, `back_nine_yards`, `total_yards`, `front_nine_meters`, `back_nine_meters`, `total_meters`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`course_id` = VALUES(`course_id`), `marker` = VALUES(`marker`), `slope` = VALUES(`slope`), `course_rating` = VALUES(`course_rating`), `front_nine_par` = VALUES(`front_nine_par`), `back_nine_par` = VALUES(`back_nine_par`), `total_par` = VALUES(`total_par`), `front_nine_yards` = VALUES(`front_nine_yards`), `back_nine_yards` = VALUES(`back_nine_yards`), `total_yards` = VALUES(`total_yards`), `front_nine_meters` = VALUES(`front_nine_meters`), `back_nine_meters` = VALUES(`back_nine_meters`), `total_meters` = VALUES(`total_meters`)"

	DBLog(sqlstr, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters)
	res, err := db.Exec(sqlstr, m.CourseId, m.Marker, m.Slope, m.CourseRating, m.FrontNinePar, m.BackNinePar, m.TotalPar, m.FrontNineYards, m.BackNineYards, m.TotalYards, m.FrontNineMeters, m.BackNineMeters, m.TotalMeters)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the CourseDetails to the database.
func (m *CourseDetails) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the CourseDetails to the database, but tries to update
// on unique constraint violations.
func (m *CourseDetails) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the CourseDetails from the database.
func (m *CourseDetails) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM course_details WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// CourseDetailsById retrieves a row from 'course_details' as a CourseDetails.
//
// Generated from primary key.
func CourseDetailsById(db DB, id int) (*CourseDetails, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_" + CourseDetailsTableName + "_by_id"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `course_id`, `marker`, `slope`, `course_rating`, `front_nine_par`, `back_nine_par`, `total_par`, `front_nine_yards`, `back_nine_yards`, `total_yards`, `front_nine_meters`, `back_nine_meters`, `total_meters` " +
		"FROM course_details " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m CourseDetails
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

type courseDetailsPKWherer struct {
	ids []any
}

func (m courseDetailsPKWherer) Where() (string, []any) {
	return "`id` = ?", m.ids
}

// Patch updates the CourseDetails in the database.
//
// Generated from primary key.
func (m *CourseDetails) Patch(db DB, newT *CourseDetails) error {
	if newT == nil {
		return errors.New("new primary is nil")
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("patch_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	res, err := patcher.NewDiffSQLPatch(
		m,
		newT,
		patcher.WithTable(CourseDetailsTableName),
		patcher.WithWhere(&courseDetailsPKWherer{
			ids: []any{m.Id},
		}),
		patcher.WithIgnoredFields(
			"Id",
		),
	)
	if err != nil {
		switch {
		case errors.Is(err, patcher.ErrNoChanges):
			return nil
		default:
			return fmt.Errorf("new diff sql patch: %w", err)
		}
	}

	sqlstr, args, err := res.GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to generate patch: %w", err)
	}

	DBLog(sqlstr, args...)
	_, err = db.Exec(sqlstr, args...)
	if err != nil {
		return fmt.Errorf("failed to execute patch: %w", err)
	}

	return nil
}

// GetCourseIdCourse Gets an instance of Course
//
// Generated from constraint course_details_course_id_fk
func (m *CourseDetails) GetCourseIdCourse(db DB) (*Course, error) {
	return CourseById(db, m.CourseId)
}

// GetAllCourseDetailss retrieves all rows from 'course_details' as a slice of CourseDetails.
//
// Generated from table 'course_details'.
func GetAllCourseDetailss(db DB, filters ...any) ([]*CourseDetails, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_all_" + CourseDetailsTableName))
	defer t.ObserveDuration()

	args := make([]any, 0)
	builder := new(strings.Builder)
	builder.WriteString("SELECT t.id, t.course_id, t.marker, t.slope, t.course_rating, t.front_nine_par, t.back_nine_par, t.total_par, t.front_nine_yards, t.back_nine_yards, t.total_yards, t.front_nine_meters, t.back_nine_meters, t.total_meters")

	if len(filters) > 0 {
		for _, filter := range filters {
			joiner, ok := filter.(patcher.Joiner)
			if ok {
				joinSql, joinArgs := joiner.Join()
				builder.WriteString(joinSql)
				args = append(args, joinArgs...)
			}
		}
	}

	builder.WriteString("\nFROM course_details t")

	if len(filters) > 0 {
		builder.WriteString("\nWHERE\n")
		for i, filter := range filters {
			where, ok := filter.(patcher.Wherer)
			if ok {
				if i > 0 {
					wtStr := patcher.WhereTypeAnd
					if wt, ok := filter.(patcher.WhereTyper); ok {
						wtStr = wt.WhereType()
					}
					builder.WriteString(string(" " + wtStr + " "))
				}
				whereSql, whereArgs := where.Where()
				builder.WriteString(whereSql)
				builder.WriteString("\n")
				args = append(args, whereArgs...)
			}
		}
	}

	sqlstr := builder.String()
	DBLog(sqlstr, args...)

	m := make([]*CourseDetails, 0)
	if err := db.Select(&m, sqlstr, args...); err != nil {
		return nil, fmt.Errorf("failed to get all CourseDetails: %w", err)
	}

	return m, nil
}
