// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"strings"

	"github.com/jacobbrewer1/patcher"
	"github.com/jacobbrewer1/patcher/inserter"
	"github.com/prometheus/client_golang/prometheus"
)

const (
	// CourseTableName is the name of the table for the Course model.
	CourseTableName = "course"
)

// Course represents a row from 'course'.
type Course struct {
	Id     int    `db:"id,pk,autoinc"`
	ClubId int    `db:"club_id"`
	Name   string `db:"name"`
}

// Insert inserts the Course to the database.
func (m *Course) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_" + CourseTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO course (" +
		"`club_id`, `name`" +
		") VALUES (" +
		"?, ?" +
		")"

	DBLog(sqlstr, m.ClubId, m.Name)
	res, err := db.Exec(sqlstr, m.ClubId, m.Name)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func InsertManyCourses(db DB, ms ...*Course) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_" + CourseTableName))
	defer t.ObserveDuration()

	vals := make([]any, 0, len(ms))
	for _, m := range ms {
		// Dereference the pointer to get the struct value.
		vals = append(vals, any(*m))
	}

	sqlstr, args, err := inserter.NewBatch(vals, inserter.WithTable(CourseTableName)).GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to create batch insert: %w", err)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *Course) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the Course in the database.
func (m *Course) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_" + CourseTableName))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE course " +
		"SET `club_id` = ?, `name` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.ClubId, m.Name, m.Id)
	res, err := db.Exec(sqlstr, m.ClubId, m.Name, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the Course to the database, and tries to update
// on unique constraint violations.
func (m *Course) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_" + CourseTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO course (" +
		"`club_id`, `name`" +
		") VALUES (" +
		"?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`club_id` = VALUES(`club_id`), `name` = VALUES(`name`)"

	DBLog(sqlstr, m.ClubId, m.Name)
	res, err := db.Exec(sqlstr, m.ClubId, m.Name)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the Course to the database.
func (m *Course) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the Course to the database, but tries to update
// on unique constraint violations.
func (m *Course) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the Course from the database.
func (m *Course) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_" + CourseTableName))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM course WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// CourseById retrieves a row from 'course' as a Course.
//
// Generated from primary key.
func CourseById(db DB, id int) (*Course, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_" + CourseTableName + "_by_id"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `club_id`, `name` " +
		"FROM course " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m Course
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

type coursePKWherer struct {
	ids []any
}

func (m coursePKWherer) Where() (string, []any) {
	return "`id` = ?", m.ids
}

// Patch updates the Course in the database.
//
// Generated from primary key.
func (m *Course) Patch(db DB, newT *Course) error {
	if newT == nil {
		return errors.New("new primary is nil")
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("patch_" + CourseTableName))
	defer t.ObserveDuration()

	res, err := patcher.NewDiffSQLPatch(
		m,
		newT,
		patcher.WithTable(CourseTableName),
		patcher.WithWhere(&coursePKWherer{
			ids: []any{m.Id},
		}),
		patcher.WithIgnoredFields(
			"Id",
		),
	)
	if err != nil {
		switch {
		case errors.Is(err, patcher.ErrNoChanges):
			return nil
		default:
			return fmt.Errorf("new diff sql patch: %w", err)
		}
	}

	sqlstr, args, err := res.GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to generate patch: %w", err)
	}

	DBLog(sqlstr, args...)
	_, err = db.Exec(sqlstr, args...)
	if err != nil {
		return fmt.Errorf("failed to execute patch: %w", err)
	}

	return nil
}

// GetClubIdClub Gets an instance of Club
//
// Generated from constraint course_club_id_fk
func (m *Course) GetClubIdClub(db DB) (*Club, error) {
	return ClubById(db, m.ClubId)
}

// GetAllCourses retrieves all rows from 'course' as a slice of Course.
//
// Generated from table 'course'.
func GetAllCourses(db DB, filters ...any) ([]*Course, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_all_" + CourseTableName))
	defer t.ObserveDuration()

	args := make([]any, 0)
	builder := new(strings.Builder)
	builder.WriteString("SELECT t.id, t.club_id, t.name")

	if len(filters) > 0 {
		for _, filter := range filters {
			joiner, ok := filter.(patcher.Joiner)
			if ok {
				joinSql, joinArgs := joiner.Join()
				builder.WriteString(joinSql)
				args = append(args, joinArgs...)
			}
		}
	}

	builder.WriteString("\nFROM course t")

	if len(filters) > 0 {
		builder.WriteString("\nWHERE\n")
		for i, filter := range filters {
			where, ok := filter.(patcher.Wherer)
			if ok {
				if i > 0 {
					wtStr := patcher.WhereTypeAnd
					if wt, ok := filter.(patcher.WhereTyper); ok {
						wtStr = wt.WhereType()
					}
					builder.WriteString(string(" " + wtStr + " "))
				}
				whereSql, whereArgs := where.Where()
				builder.WriteString(whereSql)
				builder.WriteString("\n")
				args = append(args, whereArgs...)
			}
		}
	}

	sqlstr := builder.String()
	DBLog(sqlstr, args...)

	m := make([]*Course, 0)
	if err := db.Select(&m, sqlstr, args...); err != nil {
		return nil, fmt.Errorf("failed to get all Course: %w", err)
	}

	return m, nil
}
