// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"strings"

	"github.com/jacobbrewer1/patcher"
	"github.com/jacobbrewer1/patcher/inserter"
	"github.com/prometheus/client_golang/prometheus"
)

const (
	// HoleTableName is the name of the table for the Hole model.
	HoleTableName = "hole"
)

// Hole represents a row from 'hole'.
type Hole struct {
	Id             int `db:"id,pk,autoinc"`
	CourseId       int `db:"course_id"`
	Number         int `db:"number"`
	Par            int `db:"par"`
	Stroke         int `db:"stroke"`
	DistanceYards  int `db:"distance_yards"`
	DistanceMeters int `db:"distance_meters"`
}

// Insert inserts the Hole to the database.
func (m *Hole) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_" + HoleTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO hole (" +
		"`course_id`, `number`, `par`, `stroke`, `distance_yards`, `distance_meters`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters)
	res, err := db.Exec(sqlstr, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func (m *Hole) InsertHoleWithPK(db DB) error {
	if !m.IsPrimaryKeySet() {
		return ErrNoPK
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_with_ids_" + HoleTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO hole (" +
		"`id`, `course_id`, `number`, `par`, `stroke`, `distance_yards`, `distance_meters`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.Id, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters)
	_, err := db.Exec(sqlstr, m.Id, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters)
	return err
}

func InsertManyHoles(db DB, ms ...*Hole) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_" + HoleTableName))
	defer t.ObserveDuration()

	vals := make([]any, 0, len(ms))
	for _, m := range ms {
		// Dereference the pointer to get the struct value.
		vals = append(vals, any(*m))
	}

	sqlstr, args, err := inserter.NewBatch(vals, inserter.WithTable(HoleTableName)).GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to create batch insert: %w", err)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *Hole) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the Hole in the database.
func (m *Hole) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_" + HoleTableName))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE hole " +
		"SET `course_id` = ?, `number` = ?, `par` = ?, `stroke` = ?, `distance_yards` = ?, `distance_meters` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters, m.Id)
	res, err := db.Exec(sqlstr, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the Hole to the database, and tries to update
// on unique constraint violations.
func (m *Hole) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_" + HoleTableName))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO hole (" +
		"`course_id`, `number`, `par`, `stroke`, `distance_yards`, `distance_meters`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`course_id` = VALUES(`course_id`), `number` = VALUES(`number`), `par` = VALUES(`par`), `stroke` = VALUES(`stroke`), `distance_yards` = VALUES(`distance_yards`), `distance_meters` = VALUES(`distance_meters`)"

	DBLog(sqlstr, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters)
	res, err := db.Exec(sqlstr, m.CourseId, m.Number, m.Par, m.Stroke, m.DistanceYards, m.DistanceMeters)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the Hole to the database.
func (m *Hole) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the Hole to the database, but tries to update
// on unique constraint violations.
func (m *Hole) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the Hole from the database.
func (m *Hole) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_" + HoleTableName))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM hole WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// HoleById retrieves a row from 'hole' as a Hole.
//
// Generated from primary key.
func HoleById(db DB, id int) (*Hole, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_" + HoleTableName + "_by_id"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `course_id`, `number`, `par`, `stroke`, `distance_yards`, `distance_meters` " +
		"FROM hole " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m Hole
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

type holePKWherer struct {
	ids []any
}

func (m holePKWherer) Where() (string, []any) {
	return "`id` = ?", m.ids
}

// Patch updates the Hole in the database.
//
// Generated from primary key.
func (m *Hole) Patch(db DB, newT *Hole) error {
	if newT == nil {
		return errors.New("new primary is nil")
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("patch_" + HoleTableName))
	defer t.ObserveDuration()

	res, err := patcher.NewDiffSQLPatch(
		m,
		newT,
		patcher.WithTable(HoleTableName),
		patcher.WithWhere(&holePKWherer{
			ids: []any{m.Id},
		}),
		patcher.WithIgnoredFields(
			"Id",
		),
	)
	if err != nil {
		switch {
		case errors.Is(err, patcher.ErrNoChanges):
			return nil
		default:
			return fmt.Errorf("new diff sql patch: %w", err)
		}
	}

	sqlstr, args, err := res.GenerateSQL()
	if err != nil {
		return fmt.Errorf("failed to generate patch: %w", err)
	}

	DBLog(sqlstr, args...)
	_, err = db.Exec(sqlstr, args...)
	if err != nil {
		return fmt.Errorf("failed to execute patch: %w", err)
	}

	return nil
}

// GetCourseIdCourse Gets an instance of Course
//
// Generated from constraint hole_course_id_fk
func (m *Hole) GetCourseIdCourse(db DB) (*Course, error) {
	return CourseById(db, m.CourseId)
}

// GetAllHoles retrieves all rows from 'hole' as a slice of Hole.
//
// Generated from table 'hole'.
func GetAllHoles(db DB, filters ...any) ([]*Hole, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("get_all_" + HoleTableName))
	defer t.ObserveDuration()

	args := make([]any, 0)
	builder := new(strings.Builder)
	builder.WriteString("SELECT t.id, t.course_id, t.number, t.par, t.stroke, t.distance_yards, t.distance_meters")

	if len(filters) > 0 {
		for _, filter := range filters {
			joiner, ok := filter.(patcher.Joiner)
			if ok {
				joinSql, joinArgs := joiner.Join()
				builder.WriteString(joinSql)
				args = append(args, joinArgs...)
			}
		}
	}

	builder.WriteString("\nFROM hole t")

	if len(filters) > 0 {
		builder.WriteString("\nWHERE\n")
		for i, filter := range filters {
			where, ok := filter.(patcher.Wherer)
			if ok {
				if i > 0 {
					wtStr := patcher.WhereTypeAnd
					if wt, ok := filter.(patcher.WhereTyper); ok {
						wtStr = wt.WhereType()
					}
					builder.WriteString(string(" " + wtStr + " "))
				}
				whereSql, whereArgs := where.Where()
				builder.WriteString(whereSql)
				builder.WriteString("\n")
				args = append(args, whereArgs...)
			}
		}
	}

	sqlstr := builder.String()
	DBLog(sqlstr, args...)

	m := make([]*Hole, 0)
	if err := db.Select(&m, sqlstr, args...); err != nil {
		return nil, fmt.Errorf("failed to get all Hole: %w", err)
	}

	return m, nil
}
