// Code generated by mockery. DO NOT EDIT.

package processor

import (
	models "github.com/jacobbrewer1/golf-data/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// SaveClub provides a mock function with given fields: club
func (_m *MockRepository) SaveClub(club *models.Club) error {
	ret := _m.Called(club)

	if len(ret) == 0 {
		panic("no return value specified for SaveClub")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Club) error); ok {
		r0 = rf(club)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
