load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "api",
    srcs = [
        "client.go",
        "gen.go",
        "server.go",
        "types.go",
    ],
    importpath = "github.com/jacobbrewer1/golf-data/pkg/apis/specs/api",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_gorilla_mux//:mux",
        "@com_github_jacobbrewer1_pagefilter//common",
        "@com_github_jacobbrewer1_uhttp//:uhttp",
        "@com_github_jacobbrewer1_uhttp//common",
        "@com_github_jacobbrewer1_web//:web",
        "@com_github_jacobbrewer1_web//logging",
        "@com_github_jacobbrewer1_web//metrics",
        "@com_github_oapi_codegen_runtime//:runtime",
        "@com_github_oapi_codegen_runtime//types",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/promauto",
    ],
)
