// Package dataapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/jacobbrewer1/uhttp"
	"github.com/jacobbrewer1/uhttp/common"
	"github.com/jacobbrewer1/web/logging"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all clubs
	// GetClubs (GET /clubs)
	GetClubs(l *slog.Logger, r *http.Request, params *GetClubsParams) (*GetClubsResponse, error)
}

const (
	loggingKeyError = "err"
)

var (
	// TotalRequests is a counter for the total number of requests by ALL operations.
	TotalRequests = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "total_requests",
		Help: "Total number of requests",
	}, []string{"code", "method"})

	// GetClubsTotalRequests is a counter for the total number of requests for GetClubs.
	GetClubsTotalRequests = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "getclubs_total_requests",
		Help: "Total number of requests for GetClubs",
	}, []string{"code", "method"})

	// GetClubsRequestDuration is a histogram for the request duration for GetClubs.
	GetClubsRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "getclubs_request_duration_seconds",
		Help:    "Request duration in seconds for GetClubs",
		Buckets: prometheus.DefBuckets,
	}, []string{"code", "method"})

	// GetClubsResponseSize is a histogram for the response size for GetClubs.
	GetClubsResponseSize = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "getclubs_response_size_bytes",
		Help:    "Response size in bytes for GetClubs",
		Buckets: prometheus.DefBuckets,
	}, []string{"code", "method"})
)

type RateLimiterFunc = func(http.ResponseWriter, context.Context) error
type ErrorHandlerFunc = func(context.Context, *slog.Logger, http.ResponseWriter, error)

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	l *slog.Logger

	authz       ServerInterface
	handler     ServerInterface
	rateLimiter RateLimiterFunc

	errorHandlerFunc ErrorHandlerFunc
	isInternalAPI    bool
}

// WithLogger sets the logger for the server.
func WithLogger(l *slog.Logger) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.l = l
	}
}

// WithAuthorization applies the passed authorization middleware to the server.
func WithAuthorization(authz ServerInterface) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.authz = authz
	}
}

// WithRateLimiter applies the rate limiter middleware to routes with x-global-rate-limit.
func WithRateLimiter(rateLimiter RateLimiterFunc) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.rateLimiter = rateLimiter
	}
}

// WithErrorHandlerFunc sets the error handler function for the server.
func WithErrorHandlerFunc(errorHandlerFunc ErrorHandlerFunc) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.errorHandlerFunc = errorHandlerFunc
	}
}

// WithInternalAPI sets the server as an internal API.
func WithInternalAPI(isInternalAPI bool) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.isInternalAPI = isInternalAPI
	}
}

// ServerOption represents an optional feature applied to the server.
type ServerOption func(s *ServerInterfaceWrapper)

// GetClubs operation middleware
func (siw *ServerInterfaceWrapper) GetClubs(w http.ResponseWriter, r *http.Request) {
	l := logging.LoggerFromRequest(siw.l, r)
	l = l.With(
		slog.String(logging.KeyHandler, "GetClubs"),
	)

	ctx := r.Context()
	cw := uhttp.NewResponseWriter(w,
		uhttp.WithDefaultStatusCode(http.StatusOK),
		uhttp.WithDefaultHeader(uhttp.HeaderRequestID, uhttp.RequestIDFromContext(ctx)),
		uhttp.WithDefaultHeader(uhttp.HeaderContentType, uhttp.ContentTypeJSON),
	)

	// Parameter object where we will unmarshal all parameters from the context
	params := new(GetClubsParams)

	// ------------- Optional query parameter "limit" -------------
	if err := runtime.BindQueryParameter(
		"form",
		true,
		false,
		"limit",
		r.URL.Query(),
		&params.Limit,
	); err != nil {
		siw.errorHandlerFunc(ctx, l, cw, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "last_val" -------------
	if err := runtime.BindQueryParameter(
		"form",
		true,
		false,
		"last_val",
		r.URL.Query(),
		&params.LastVal,
	); err != nil {
		siw.errorHandlerFunc(ctx, l, cw, &InvalidParamFormatError{ParamName: "last_val", Err: err})
		return
	}

	// ------------- Optional query parameter "last_id" -------------
	if err := runtime.BindQueryParameter(
		"form",
		true,
		false,
		"last_id",
		r.URL.Query(),
		&params.LastId,
	); err != nil {
		siw.errorHandlerFunc(ctx, l, cw, &InvalidParamFormatError{ParamName: "last_id", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if err := runtime.BindQueryParameter(
		"form",
		true,
		false,
		"offset",
		r.URL.Query(),
		&params.Offset,
	); err != nil {
		siw.errorHandlerFunc(ctx, l, cw, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------
	if err := runtime.BindQueryParameter(
		"form",
		true,
		false,
		"sort_by",
		r.URL.Query(),
		&params.SortBy,
	); err != nil {
		siw.errorHandlerFunc(ctx, l, cw, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------
	if err := runtime.BindQueryParameter(
		"form",
		true,
		false,
		"sort_dir",
		r.URL.Query(),
		&params.SortDir,
	); err != nil {
		siw.errorHandlerFunc(ctx, l, cw, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------
	if err := runtime.BindQueryParameter(
		"form",
		true,
		false,
		"name",
		r.URL.Query(),
		&params.Name,
	); err != nil {
		siw.errorHandlerFunc(ctx, l, cw, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Invoke the callback with all the unmarshalled arguments
	resp, err := siw.handler.GetClubs(l, r, params)
	if err != nil {
		siw.errorHandlerFunc(ctx, l, cw, err)
		return
	}

	w.Header().Set(uhttp.HeaderContentType, "application/json; charset=utf-8")
	w.WriteHeader(200)
	err = json.NewEncoder(w).Encode(resp)
	if err != nil {
		siw.errorHandlerFunc(ctx, l, cw, err)
		return
	}
}

// parseRequestBody parses the request body into the expected type.
func (siw *ServerInterfaceWrapper) parseRequestBody(r *http.Request, dest any) error {
	if r.Body == http.NoBody {
		return &UnmarshalingBodyError{Err: errors.New("empty body")}
	}

	contentType := r.Header.Get(uhttp.HeaderContentType)
	switch contentType {
	case "application/json":
		decoder := json.NewDecoder(r.Body)
		if !siw.isInternalAPI {
			decoder.DisallowUnknownFields()
		}
		if err := decoder.Decode(dest); err != nil {
			e := new(uhttp.HTTPError)
			if errors.As(err, &e) {
				return err
			}
			return &UnmarshalingBodyError{Err: err}
		}
	case "application/x-www-form-urlencoded":
		bdy, err := io.ReadAll(r.Body)
		if err != nil {
			e := new(uhttp.HTTPError)
			if errors.As(err, &e) {
				return err
			}
			return &UnmarshalingBodyError{Err: err}
		}

		body, ok := dest.(*openapi_types.File)
		if !ok {
			e := new(uhttp.HTTPError)
			if errors.As(err, &e) {
				return err
			}
			return &UnmarshalingBodyError{Err: fmt.Errorf("expected *openapi_types.FormData, got %T", dest)}
		}

		body.InitFromBytes(bdy, "file")
	default:
		return &UnsupportedContentTypeError{ContentType: contentType}
	}

	return nil
}

// handleError handles returning a correctly-formatted error to the API caller.
func handleError(ctx context.Context, l *slog.Logger, w http.ResponseWriter, err error) {
	l.Error("Error handling request", slog.String(loggingKeyError, err.Error()))

	e := new(uhttp.HTTPError)
	if errors.As(err, &e) {
		e.RequestId = uhttp.RequestIDFromContext(ctx)
		_ = encodeErrorResponse(w, e)
		return
	}

	code := http.StatusInternalServerError
	if e, ok := err.(uhttp.StatusCoder); ok {
		code = e.StatusCode()
	}

	_ = encodeErrorResponse(w, &uhttp.HTTPError{
		ErrorMessage: common.ErrorMessage{
			Title:     http.StatusText(code),
			Detail:    "error handling request",
			Status:    code,
			RequestId: uhttp.RequestIDFromContext(ctx),
			Details: []any{
				err.Error(),
			},
		},
	})
}

// encodeErrorResponse encodes input response as an RFC-7807-compliant response to w.
func encodeErrorResponse(w http.ResponseWriter, response any) error {
	w.Header().Set(uhttp.HeaderContentType, "application/problem+json; charset=utf-8")

	if e, ok := response.(uhttp.StatusCoder); ok {
		w.WriteHeader(e.StatusCode())
	}

	return json.NewEncoder(w).Encode(response)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnsupportedContentTypeError struct {
	ContentType string
}

func (e *UnsupportedContentTypeError) StatusCode() int {
	return http.StatusUnsupportedMediaType
}

func (e *UnsupportedContentTypeError) Error() string {
	return fmt.Sprintf("Unsupported content type: %s", e.ContentType)
}

type UnmarshalingBodyError struct {
	Err error
}

func (e *UnmarshalingBodyError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *UnmarshalingBodyError) Error() string {
	return fmt.Sprintf("Error unmarshaling request body: %s", e.Err.Error())
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// RegisterUnauthedHandlers registers any api handlers which do not have any authentication on them. Most services will not have any.
func RegisterUnauthedHandlers(router *mux.Router, si ServerInterface, opts ...ServerOption) {
	wrapper := ServerInterfaceWrapper{
		l:                slog.Default(),
		authz:            nil,
		handler:          si,
		rateLimiter:      nil,
		errorHandlerFunc: handleError,
	}

	for _, opt := range opts {
		if opt == nil {
			continue
		}
		opt(&wrapper)
	}

	router.Use(uhttp.AuthHeaderToContextMux())
	router.Use(uhttp.GenerateOrCopyRequestIDMux())

	router.Methods(http.MethodGet).
		Path("/clubs").
		Handler(uhttp.WrapHandler(
			wrapper.GetClubs,
			uhttp.InstrumentCounter(TotalRequests),
			uhttp.InstrumentCounter(GetClubsTotalRequests),
			uhttp.InstrumentDuration(GetClubsRequestDuration),
			uhttp.InstrumentResponseSize(GetClubsResponseSize),
		))

}
